name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions that allow GitHub Actions to create a deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allows concurrent deployment runs
concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  # The 'build' job bundles the React app and uploads the artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The contents of the dist folder are uploaded as the artifact
          path: './dist'
          
  # The 'deploy' job takes the uploaded artifact and deploys it to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
